# Generated by Django 3.0.2 on 2023-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckdApp', '0002_auto_20200205_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ckdmodel',
            name='Albumin',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
